const list = [
  
    {
        Id: 1,
        title: "linginier shop",
        description: "small",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/10.jpg',
        amount: '',
    },
    {
        Id: 2,
        title: "linginier shop",
        description: "Medium",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/11.jpg',
        amount: '',
    },
    {
        Id: 3,
        title: "linginier shop",
        description: "big",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/17.jpg',
        amount: '',
    },
    {
        Id: 4,
        title: "linginier shop",
        description: "small",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/16.jpg',
        amount: '',
    },
    {
        Id: 5,
        title: "linginier shop",
        description: "Medium",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/10.jpg',
        amount: '',
    },
    {
        Id: 6,
        title: "linginier shop",
        description: "big",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/18.jpg',
        amount: '',
    },
    {
        Id: 7,
        title: "linginier shop",
        description: "small",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: "./picture/19.jpg",
        amount: '',
    },
    {
        Id: 8,
        title: "linginier shop",
        description: "Medium",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/10.jpg',
        amount: '',
    },
    {
        Id: 9,
        title: "linginier shop",
        description: "big",
        date: "11 / may / 2022",
        price: 3000,
        category: "",
        status: "",
        Img: './picture/11.jpg',
        amount: '',
    }
]



export default list
